from __future__ import annotations
import sys
from pathlib import Path

# Add project root to sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import argparse
import pandas as pd
from src.evaluation.llm_judge import LLMJudge
from src.evaluation.human_validation import HumanVsLLMValidator

def main():
    parser = argparse.ArgumentParser(description="Run LLM Judge and Human Validation workflows")
    parser.add_argument("--preds-csv", default="reports/golden_evaluation_predictions.csv", help="Path to evaluation predictions CSV")
    parser.add_argument("--val-csv", default="data/human_judge_validation.csv", help="Path to human validation CSV")
    args = parser.parse_args()

    print("=== Step 1: LLM-as-a-Judge Evaluation on Golden Predictions ===")
    if Path(args.preds_csv).exists():
        df = pd.read_csv(args.preds_csv)
        judge = LLMJudge()
        
        sample_size = min(50, len(df))
        sample_df = df.sample(sample_size, random_state=42)
        print(f"Auditing sample of {sample_size} predictions with 5D LLM Judge rubric...")
        
        scores = []
        for _, row in sample_df.iterrows():
            j_score = judge.evaluate_reply(
                query=str(row["customer_text"]),
                intent=str(row.get("agent_pred_intent", "")),
                action=str(row.get("agent_pred_action", "")),
                reply=str(row["agent_reply"]),
                evidence_text=str(row.get("reference_reply", ""))
            )
            scores.append(j_score)
            
        avg_corr = sum(s.correctness for s in scores) / len(scores)
        avg_ground = sum(s.groundedness for s in scores) / len(scores)
        avg_help = sum(s.helpfulness for s in scores) / len(scores)
        avg_brand = sum(s.brand_consistency for s in scores) / len(scores)
        avg_safe = sum(s.safety for s in scores) / len(scores)
        avg_overall = sum(s.average_score for s in scores) / len(scores)
        
        out_judge_report = "reports/llm_judge_evaluation.md"
        with open(out_judge_report, "w", encoding="utf-8") as f:
            f.write("# LLM-as-a-Judge Audit Report\n\n")
            f.write(f"Evaluated sample size: **{sample_size} responses** generated by the AI SupportAgent.\n\n")
            f.write("## 1. Rubric Dimension Averages (1.0 - 5.0 Scale)\n\n")
            f.write("| Dimension | Average Score | Operational Target | Status |\n")
            f.write("| :--- | :---: | :---: | :---: |\n")
            f.write(f"| **Correctness** | `{avg_corr:.2f}` / 5.0 | ≥ 4.0 | {'PASS' if avg_corr >= 4.0 else 'WARN'} |\n")
            f.write(f"| **Groundedness** | `{avg_ground:.2f}` / 5.0 | ≥ 4.0 | {'PASS' if avg_ground >= 4.0 else 'WARN'} |\n")
            f.write(f"| **Helpfulness** | `{avg_help:.2f}` / 5.0 | ≥ 4.0 | {'PASS' if avg_help >= 4.0 else 'WARN'} |\n")
            f.write(f"| **Brand Consistency** | `{avg_brand:.2f}` / 5.0 | ≥ 4.2 | {'PASS' if avg_brand >= 4.2 else 'WARN'} |\n")
            f.write(f"| **Safety** | `{avg_safe:.2f}` / 5.0 | = 5.0 | {'PASS' if avg_safe >= 4.9 else 'FAIL'} |\n")
            f.write(f"| **Composite Overall** | `{avg_overall:.2f}` / 5.0 | ≥ 4.2 | {'PASS' if avg_overall >= 4.2 else 'WARN'} |\n\n")
            f.write("## 2. Sample Qualitative Audit Logs\n\n")
            for idx, s in enumerate(scores[:5], 1):
                f.write(f"### Example #{idx}\n")
                f.write(f"- **Overall Score**: {s.average_score}/5.0\n")
                f.write(f"- **Correctness**: {s.correctness} | **Groundedness**: {s.groundedness} | **Helpfulness**: {s.helpfulness}\n")
                f.write(f"- **Brand**: {s.brand_consistency} | **Safety**: {s.safety}\n")
                f.write(f"- **Judge Rationale**: {s.reasoning}\n\n")
                
        print(f"LLM Judge report saved to {out_judge_report}")
    else:
        print(f"Notice: {args.preds_csv} not found. Run scripts/run_evaluation.py first.")

    print("\n=== Step 2: Human-vs-LLM Judge Statistical Agreement Workflow ===")
    validator = HumanVsLLMValidator(validation_dataset_path=args.val_csv)
    val_results = validator.run_validation(output_report_path="reports/human_judge_agreement.md")
    
    print("\nJudge evaluation and human validation workflows completed successfully!")

if __name__ == "__main__":
    main()
